#监控服务器连接配置信息 xx.xx.xx.xx
instances:
  configs:
    - host: 106.
      user: root
      passwd: id_rsa
    - host: 106.
      user: root
      passwd: id_rs

spring:
  datasource:
    driver-class-name:
  redis:
    host: 106.
    port: 6379
    password: xxxxx
server:
  port: 80
